### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'state_dim' error

### ISSUE THREAD

**Issue by Xijieupenn** [hanruihua/rl_rvo_nav#1]
When training to 250 epochs, I get the following error.
![Screenshot from 2022-04-15 13-22-54](https://user-images.githubusercontent.com/103215905/163601579-d85b442a-b013-4c9f-9fa3-047d81db9546.png)

Could you help me see what the mistake might be?

**Comment by hanruihua** [comment]
Hi, thanks for pointing this out. The main reason is the set error of argument _policy_dict_ in the **policy_test** function. If the policy name is with _"check_point"_, the _policy_dict_ should be True. Otherwise, it should be False. 

I have fixed this bug, and you can try to train with the letest version. Thanks

**Comment by Xijieupenn** [comment]
Thank you so much. I will try to retrain it. However, I just met a new problem when trying to test my newly trained model. 
![Screenshot from 2022-04-16 18-22-23](https://user-images.githubusercontent.com/103215905/163693111-5444baa5-ac69-4516-a98f-ffb8c5936e8e.png)

I do not know why the model cannot be pickled. I believe the path to the model is correct.

**Comment by hanruihua** [comment]
Hi, I have tested the _policy test_ function in the policy_test.py, and there is no error like yours. 

The pickle.load() function is to load the argments that saved in the pickle.dump() in train_process.py, and is only related to the python module [pickle](https://docs.python.org/3/library/pickle.html). You can test the pickle.dump() and pickle.load() solely to find the main reason. If there are still this error, you may try the other version of pickle

**Comment by Xijieupenn** [comment]
The new version works fine. Thank you so much.
