### ISSUE TITLE
matplotlib在清除对象所有文本时报错AttributeError: 'ArtistList' object has no attribute 'clear' 

### ISSUE THREAD

**Issue by zks204** [hanruihua/rl_rvo_nav#10]
运行代码时报错：AttributeError: 'ArtistList' object has no attribute 'clear'  。 这个错误是由于matplotlib的版本太高吗？？我的版本是matplotlib==3.5.1。

**Comment by hanruihua** [comment]
是的  应该是matplotlib 版本太高了  降低下版本试试

**Comment by hanruihua** [comment]
> 
修改了一下intelligent-robot-simulator （  https://github.com/hanruihua/intelligent-robot-simulator  ）
可以适配最新版本的matplotlib了  可以重新安装一下

**Comment by zks204** [comment]
非常感谢发自我的手机-------- 原始邮件 --------发件人： Han ***@***.***>日期： 2023年3月17日周五 中午11:41收件人： hanruihua/rl_rvo_nav ***@***.***>抄送： zks204 ***@***.***>, Author ***@***.***>主    题： Re: [hanruihua/rl_rvo_nav] matplotlib在清除对象所有文本时报错AttributeError: 'ArtistList' object has no attribute 'clear'  (Issue #10)


修改了一下intelligent-robot-simulator （https://github.com/hanruihua/intelligent-robot-simulator），可以适配最新版本的matplotlib了  可以重新安装一下
