### ISSUE TITLE
reward change chart

### ISSUE THREAD

**Issue by FADEAWAY114** [hanruihua/rl_rvo_nav#11]
How do I get the final reward change chart?

**Comment by hanruihua** [comment]
Hi,  the average reward of each robot is saved in the list:  ep_ret_list_mean.  (https://github.com/hanruihua/rl_rvo_nav/blob/main/rl_rvo_nav/policy_train/multi_ppo.py#L256), you can plot the mean at each epoch to see the reward change chart.

**Comment by FADEAWAY114** [comment]
> 嗨，每个机器人的平均奖励保存在列表中：ep_ret_list_mean。（https://github.com/hanruihua/rl_rvo_nav/blob/main/rl_rvo_nav/policy_train/multi_ppo.py#L256），您可以绘制每个时期的平均值以查看奖励变化图。

Thank you. Please ask which file is required for the example with moving obstacles？

**Comment by hanruihua** [comment]
You can change world name to be [dynamic_obs_test.yaml](https://github.com/hanruihua/rl_rvo_nav/blob/main/gym_env/dynamic_obs_test.yaml) to configure the environment with dynamic obstacles. However, the observations may be modified.  I recommend to consider other robots as moving obstacles which is similar and easy to use.

**Comment by FADEAWAY114** [comment]
Ok thanks. I'm going to close this issue.
