### ISSUE TITLE
How do I add some static obstacles to the dynamic obstacle world?

### ISSUE THREAD

**Issue by FADEAWAY114** [hanruihua/rl_rvo_nav#13]
Hello, I want to add some static obstacles to the dynamic obstacle world, so I modified the “**dynamic_obs_test.yaml**” file and modified it as follows. But when running, there are no static obstacles, please how should I set it up to run correctly.
![4](https://user-images.githubusercontent.com/105548396/231118985-7100a40e-ef7e-4ada-9a30-ed854bf80b07.png)

**Comment by hanruihua** [comment]
The modification is wrong,  only obs_cirs can be recongnized.  you can just add the static polygon obstacles by adding the follows:

obs_polygons:
        number: 1
        vertexes_list: [  [ [4, 2], [4, 4], [3, 4], [3, 2] ], ]

**Comment by FADEAWAY114** [comment]
> 修改是错误的，只有obs_cirs可以重新识别。您可以通过添加以下内容来添加静态多边形障碍物：
> 
> obs_polygons： 数字： 1 vertexes_list： [ [ [4， 2]， [4， 4]， [3， 4]， [3， 2] ]， ]

Thank you
