### ISSUE TITLE
I cannot reproduce the result

### ISSUE THREAD

**Issue by lukeprotag** [hanruihua/rl_rvo_nav#16]
I can only obtain results in 4 robot settings, but when using weights to train 10 robots, I cannot obtain good results.

**Comment by hanruihua** [comment]
Hi 

you can try to adjust the coefficients in the reward function, which is important for the training outcome

**Comment by jijiking-hh** [comment]
Hello, I also have this question. How can 10 agents set reward functions in a dynamic environment? May I ask if you can demonstrate it

**Comment by lukeprotag** [comment]
> Hello, I also have this question. How can 10 agents set reward functions in a dynamic environment? May I ask if you can demonstrate it

In train_process.py, I found :
par_env.add_argument('--reward_parameter', type=float, default=(3.0, 0.3, 0.0, 6.0, 0.3, 3.0, -0, 0), nargs='+')

**Comment by jijiking-hh** [comment]
Thank you，actually I have also noticed this, but the correspondence between these parameters and the reward function, their actual significance, and the basis for adjustment are still unclear
