### ISSUE TITLE
SARL for multi-robot

### ISSUE THREAD

**Issue by Huyen0402** [hanruihua/rl_rvo_nav#18]
How do you implement SARL for multi-robot? Can you share source code, how to install and train for me?

**Comment by hanruihua** [comment]
Hi, SARL is implmented by this repository: https://github.com/vita-epfl/CrowdNav. We train this model and implement that in our environment. Each robot is considered as a dynamic obstalce. You can refer to that too.

**Comment by Huyen0402** [comment]
But that’s single robot. Do you need to edit code with multi-robot?

Vào Th 2, 10 thg 6, 2024 lúc 10:36 Han ***@***.***> đã viết:

**Comment by hanruihua** [comment]
Yeah, actually the only thing you need to do is to satisfy the model interface when apply the trained policy to each robot in our multi-robot systems.

**Comment by Huyen0402** [comment]
I trained single robot model, but I don't know how to "satisfy the model
interface". Can you help me? Thank you!

Vào Th 2, 10 thg 6, 2024 vào lúc 12:36 Han ***@***.***> đã
viết:

**Comment by hanruihua** [comment]
May be these two functions may help you, you can refer to these and implement by yourself: 
![image](https://github.com/hanruihua/rl_rvo_nav/assets/16113200/38aae3a9-582e-4f1b-b1f4-4a5de637c336)
![image](https://github.com/hanruihua/rl_rvo_nav/assets/16113200/ce76b0e8-c6b6-4f54-8195-68416d6c1176)
