### ISSUE TITLE
rl_rvo_nav目录下的文件在哪里调用了mranv和ir_gym呢

### ISSUE THREAD

**Issue by ZSHCRWY25** [hanruihua/rl_rvo_nav#19]
orz没理解错的话gym_env下envs文件中的mrnav以及ir_gym文件是智能体学习所用的环境，rl_rvo_nav文件下是训练智能体所用的算法，但是没有在rl_rvo_nav文件夹下的文件中发现对mrnav以及ir_gym文件的调用，这是为什么呢

**Comment by hanruihua** [comment]
mrnav 和 ir_gym  是自定义了 gym的环境，之后就是调用gym的接口来使用了，具体到代码里， gym.make 返回的环境就是 mrnav 和 ir_gym 里定义的，所使用的方法也都是文件里定义的函数

**Comment by ZSHCRWY25** [comment]
谢谢解答，还有个问题：ir_gym下用于检测震荡的osc_reward函数没有看见调用，是在哪里发挥作用的呢

**Comment by hanruihua** [comment]
这个是调试过程中尝试解决震荡写的函数，不过最后效果不是很好 就没用上
