### ISSUE TITLE
 cal_vo_exp_tim函数算出来碰撞时间为负

### ISSUE THREAD

**Issue by ZSHCRWY25** [hanruihua/rl_rvo_nav#20]
如题，设置
rel_x =8
rel_y = 4
rel_vx = 2
rel_vy = 1
r=2
计算出来两根均为负

**Comment by hanruihua** [comment]
这种情况代表已经碰撞了  会返回 inf,  参见 函数 cal_exp_tim
 
https://github.com/hanruihua/rl_rvo_nav/blob/main/gym_env/gym_env/envs/reciprocal_vel_obs.py

**Comment by ZSHCRWY25** [comment]
明白了！我将相对速度方向搞反了，我的问题，谢谢作者！
