### ISSUE TITLE
除了将自己编写的环境放入Anaconda3\Lib\site-packages\gym\envs中以外，还有别的办法注册环境吗？

### ISSUE THREAD

**Issue by ZSHCRWY25** [hanruihua/rl_rvo_nav#22]
我观察到好像执行安装程序之后并没有将rl_rvo_nav转移到Anaconda3\Lib\site-packages\gym\envs文件夹下，环境变量中也未添加\rl_rvo_nav\gym_env路径，但是在执行程序时工作路径仍然包括：当下路径、\rl_rvo_nav\gym_env路径、以及预定好的环境变量，这是如何做到的呢？

**Comment by hanruihua** [comment]
pip install -e . 的命令就是把库的路径注册到了python 库的环境变量里，可以利用命令 pip show rl_rvo_nav 看库的路径。

**Comment by ZSHCRWY25** [comment]
gym.make()报错： TypeError 'module' object is not callable，这个错误是为什么呢？在网上也没有找到合适的解决方法

**Comment by hanruihua** [comment]
> gym.make()报错： TypeError 'module' object is not callable，这个错误是为什么呢？在网上也没有找到合适的解决方法

有可能是你的文件夹的名字和库的名字重合了

**Comment by ZSHCRWY25** [comment]
但我的项目文件没有叫gym的....并且我在监视窗口发现gym下make变量报错：make=SyntaxError('invalid syntax', ('<string>', 1, 1, '<function make at 0x0000011466B88CA0>'))这有可能是版本问题吗？

**Comment by hanruihua** [comment]
是有可能   这里gym版本用的比较老了

**Comment by ZSHCRWY25** [comment]
已解决，将gym0.20.0卸载后重装就能跑了（更高版本的gym也不行）
