### ISSUE TITLE
Visual interface lag issue

### ISSUE THREAD

**Issue by lynn9966** [hanruihua/rl_rvo_nav#25]
Hello author, I have gained a lot of knowledge through studying your project. Thank you for sharing.
However, I encountered visual interface lag issues during the training process, but the program is still running normally.
May I ask where the problem lies?
![1](https://github.com/user-attachments/assets/2b960e4e-77a1-42fc-9e4e-466cdc6ae523)

**Comment by lynn9966** [comment]
Whenever the second epoch starts, the visualization interface freezes
![1](https://github.com/user-attachments/assets/6bf67d6d-5dc8-4a1c-9bd2-f8b47f242932)

**Comment by hanruihua** [comment]
Hi 

Thank you for your attention to our work.

This issue might be caused by PyCharm. You can refer to this link and try again.

https://stackoverflow.com/questions/70964332/mplot3d-plot-freezes-when-plotting-in-pycharm-professional

**Comment by lynn9966** [comment]
Thank you for your reply. I started to solve the problem as soon as you replied. You provided me with direction to solve the problem, and I tried the method of the link you provided. But it was not successful.
Furthermore, I have tried other methods along the direction you provided, but have not been successful.
I hope I haven't added the wrong location.
![1](https://github.com/user-attachments/assets/d29ceb17-2710-4efc-9cf9-1a698922fd41)

**Comment by hanruihua** [comment]
Hi,

I have tested the code in Pycharm and it works for me. You may try to upgrade the pycharm version, or update the matplotlib version.

**Comment by lynn9966** [comment]
ok
thank you！

**Comment by Olivergaohan** [comment]
@lynn9966 Hello, I have run into the same question as you. Did you solve this problem in the end? If so, what method did you use?

**Comment by Olivergaohan** [comment]
> [@lynn9966](https://github.com/lynn9966) Hello, I have run into the same question as you. Did you solve this problem in the end? If so, what method did you use?

I’ve found the root of the problem. The key lies in the render_freq parameter within the training_loop function in multi_ppo.py. For example, when the current epoch is 2 and render_freq is set to 5, no visualization will occur during this epoch. However, during such an epoch where rendering is skipped, the figure window must not be clicked—any interaction with the figure window will cause it to freeze or crash. If just simply wait, the visualization will resume and function normally once epoch 5 is reached.
