### ISSUE TITLE
在训练随机场景中的问题

### ISSUE THREAD

**Issue by PHZ-897044002** [hanruihua/rl_rvo_nav#26]
您好，
        通过您的代码，我在圆形场景中能够达到很好的效果，但是在另外两种场景中，我使用圆形场景中训练100%的10个机器人的模型效果并不是很好，是否我应该在训练时就使用10个机器人在其它两个场景进行训练，并且在训练时降低neighbors_num的数量这样是否能够提高在其它两个场景中的成功率。

**Comment by hanruihua** [comment]
你好

建议可以尝试在圆形场景后，在随机场景多训练一次。
neighbors_num的数量建议在训练时增加，在应用测试时，密集的场景可以减少neighbors_num的数量以提高成功率。

Hello,

It is recommended to try training once more on random scenes after the circular scene.
During training, it is advisable to increase the number of neighbors_num; however, during application testing, you can reduce the number of neighbors_num in dense scenes to improve the success rate.
